set(_AMENT_PACKAGE_NAME "rtmaps_ros2_bridge")
set(rtmaps_ros2_bridge_VERSION "1.1.1")
set(rtmaps_ros2_bridge_MAINTAINER "Thomas Coffy <thomas.coffy@intempora.com>")
set(rtmaps_ros2_bridge_BUILD_DEPENDS "rcutils" "rclcpp" "rclcpp_components" "std_msgs")
set(rtmaps_ros2_bridge_BUILDTOOL_DEPENDS "ament_cmake")
set(rtmaps_ros2_bridge_BUILD_EXPORT_DEPENDS "rclcpp" "rclcpp_components" "std_msgs")
set(rtmaps_ros2_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(rtmaps_ros2_bridge_EXEC_DEPENDS "rclcpp" "rclcpp_components" "std_msgs")
set(rtmaps_ros2_bridge_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(rtmaps_ros2_bridge_GROUP_DEPENDS )
set(rtmaps_ros2_bridge_MEMBER_OF_GROUPS )
set(rtmaps_ros2_bridge_DEPRECATED "")
set(rtmaps_ros2_bridge_EXPORT_TAGS)
list(APPEND rtmaps_ros2_bridge_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
